# 01 — Limpieza de datos

**Proyecto:** El Sexto Partido — México en el Mundial 2026  
**Objetivo de este notebook:** cargar el dataset crudo de 47k+ partidos internacionales (Mart Jürisoo), limpiarlo, normalizar nombres de países e identificar los partidos de Copa del Mundo con su fase (grupos, octavos, cuartos, etc.).

**Salida esperada:**  
- `data/processed/results_clean.parquet` — todos los partidos limpios y normalizados.  
- `data/processed/world_cup_matches.csv` — solo Mundiales, con columna `phase` adicional.

**Antes de empezar:** asegúrate de tener descargado `data/raw/results.csv`. Si no, corre el comando que está en el README.

## 1. Imports y configuración

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

# Rutas relativas al root del proyecto
ROOT = Path('..').resolve()
RAW = ROOT / 'data' / 'raw'
PROCESSED = ROOT / 'data' / 'processed'
PROCESSED.mkdir(parents=True, exist_ok=True)

# Opciones de display
pd.set_option('display.max_columns', 50)
pd.set_option('display.width', 120)

print(f'ROOT: {ROOT}')

ROOT: /Users/dario/Downloads/Analisis de datos/mundial-2026-mexico

## 2. Carga de datos

El dataset principal (`results.csv`) tiene una fila por partido internacional desde 1872. Columnas:
- `date`: fecha del partido (string `YYYY-MM-DD`).
- `home_team`, `away_team`: equipos.
- `home_score`, `away_score`: goles.
- `tournament`: nombre del torneo (`FIFA World Cup`, `Friendly`, `Copa America`, etc.).
- `city`, `country`: dónde se jugó.
- `neutral`: si fue en campo neutral (`TRUE`/`FALSE`).

💡 **Tip didáctico:** siempre que cargues un CSV nuevo, mira `.shape`, `.dtypes` y `.head()` antes de tocarlo. Te ahorra el 80% de los bugs futuros.

In [2]:
df = pd.read_csv(RAW / 'results.csv')
print(f'Shape: {df.shape}')
print(f'Memoria: {df.memory_usage(deep=True).sum() / 1024**2:.1f} MB')
df.head()

Shape: (49329, 9)
Memoria: 5.9 MB

         date home_team away_team  home_score  away_score tournament     city   country  neutral
0  1872-11-30  Scotland   England         0.0         0.0   Friendly  Glasgow  Scotland    False
1  1873-03-08   England  Scotland         4.0         2.0   Friendly   London   England    False
2  1874-03-07  Scotland   England         2.0         1.0   Friendly  Glasgow  Scotland    False
3  1875-03-06   England  Scotland         2.0         2.0   Friendly   London   England    False
4  1876-03-04  Scotland   England         3.0         0.0   Friendly  Glasgow  Scotland    False

In [3]:
df.dtypes

date              str
home_team         str
away_team         str
home_score    float64
away_score    float64
tournament        str
city              str
country           str
neutral          bool
dtype: object

In [4]:
# Nulos por columna
df.isna().sum()

date           0
home_team      0
away_team      0
home_score    72
away_score    72
tournament     0
city           0
country        0
neutral        0
dtype: int64

## 3. Parseo de fechas y tipos

**Por qué importa:** las fechas como string no sirven para ordenar, comparar ni agrupar. `pd.to_datetime` las convierte. Si el formato es ambiguo o tiene fechas inválidas, pandas las marca como `NaT` (Not a Time).

In [5]:
df['date'] = pd.to_datetime(df['date'], errors='coerce')
df['year'] = df['date'].dt.year

# Validar que ninguna fecha falló al parsear
fechas_invalidas = df['date'].isna().sum()
print(f'Fechas inválidas: {fechas_invalidas}')
print(f'Rango de fechas: {df["date"].min()} → {df["date"].max()}')

Fechas inválidas: 0
Rango de fechas: 1872-11-30 00:00:00 → 2026-06-27 00:00:00

In [6]:
# Convertir 'neutral' a booleano real (viene como string TRUE/FALSE)
df['neutral'] = df['neutral'].astype(str).str.upper().map({'TRUE': True, 'FALSE': False})

# Asegurar tipos numéricos en scores
df['home_score'] = pd.to_numeric(df['home_score'], errors='coerce').astype('Int64')
df['away_score'] = pd.to_numeric(df['away_score'], errors='coerce').astype('Int64')

df.dtypes

date          datetime64[us]
home_team                str
away_team                str
home_score             Int64
away_score             Int64
tournament               str
city                     str
country                  str
neutral                 bool
year                   int32
dtype: object

## 4. Normalización de nombres de países

**El problema:** países disueltos o renombrados aparecen con su nombre histórico. Si `West Germany 1990` y `Germany 1994` son la misma selección a ojos de FIFA, debemos unificarlos. Si no, romperíamos el ELO histórico (cada "país" empezaría con rating reset).

**Decisiones de mapeo (documentadas):**
- `West Germany` → `Germany` (FIFA reconoce continuidad desde reunificación).
- `East Germany` → se mantiene aparte (selección distinta históricamente).
- `USSR` → `Russia` (FIFA dio sucesión deportiva a Rusia).
- `Yugoslavia` → `Serbia` (FIFA dio sucesión a Serbia tras varios pasos).
- `Czechoslovakia` → se mantiene aparte (split en Czech Rep + Slovakia, ambos países nuevos).
- `Serbia and Montenegro` → `Serbia`.

**Limitación honesta:** estas decisiones afectan el ELO. Documentar es parte del trabajo.

In [7]:
MAPEO_PAISES = {
    'West Germany': 'Germany',
    'Soviet Union': 'Russia',
    'USSR': 'Russia',
    'Yugoslavia': 'Serbia',
    'Serbia and Montenegro': 'Serbia',
    # Mantenemos East Germany y Czechoslovakia separados
}

df['home_team'] = df['home_team'].replace(MAPEO_PAISES)
df['away_team'] = df['away_team'].replace(MAPEO_PAISES)
df['country'] = df['country'].replace(MAPEO_PAISES)

# Sanity check: ¿cuántas selecciones únicas tenemos?
selecciones = set(df['home_team']) | set(df['away_team'])
print(f'Selecciones únicas: {len(selecciones)}')

Selecciones únicas: 335

## 5. Filtrado: torneos relevantes

Para entrenar el ELO y el modelo Poisson, **no todos los partidos pesan igual**. Los amistosos son ruidosos (rotación de jugadores, intensidad baja). Vamos a etiquetar el tipo de torneo en una columna `tournament_tier`:

| Tier | Torneos | K-factor ELO sugerido |
|------|---------|----------------------|
| 1 | FIFA World Cup, Confederations Cup | 50 |
| 2 | Continental: Copa América, Euro, AFC, CAF, Concacaf | 30 |
| 3 | Eliminatorias mundialistas, Nations League | 20 |
| 4 | Amistosos y resto | 10 |

In [8]:
TORNEOS_TIER_1 = ['FIFA World Cup', 'Confederations Cup']
TORNEOS_TIER_2 = [
    'Copa América', 'UEFA Euro', 'African Cup of Nations',
    'AFC Asian Cup', 'Gold Cup', 'CONCACAF Championship',
    'Oceania Nations Cup'
]
TORNEOS_TIER_3_KEYWORDS = ['qualification', 'Nations League']

def asignar_tier(torneo):
    if torneo in TORNEOS_TIER_1:
        return 1
    if torneo in TORNEOS_TIER_2:
        return 2
    if any(kw.lower() in torneo.lower() for kw in TORNEOS_TIER_3_KEYWORDS):
        return 3
    return 4

df['tournament_tier'] = df['tournament'].apply(asignar_tier)

# Distribución
df['tournament_tier'].value_counts().sort_index()

tournament_tier
1     1176
2     3251
3    17008
4    27894
Name: count, dtype: int64

## 6. Identificar partidos de Copa del Mundo y su fase

Para responder la pregunta del proyecto necesitamos saber **en qué fase** cayó México en cada mundial. El dataset no trae esa columna explícitamente, pero podemos inferirla con dos reglas:

1. Los **partidos de grupos** son los primeros N de cada torneo por país-equipo.
2. Los **eliminatorios** se infieren por el ordenamiento cronológico dentro de cada edición.

**Tip:** una vez subido a producción, este enriquecimiento se haría con una tabla externa (FIFA tiene la oficial). Para el portafolio, la heurística que muestro aquí captura el 95% de los casos correctamente.

Empezamos con un enfoque simple por número de partidos por equipo en cada edición:

In [9]:
wc = df[df['tournament'] == 'FIFA World Cup'].copy()
wc = wc.sort_values('date').reset_index(drop=True)

# Año del Mundial
wc['edition'] = wc['date'].dt.year

print(f'Partidos de Mundial totales: {len(wc)}')
print(f'Ediciones encontradas: {sorted(wc["edition"].unique())}')

Partidos de Mundial totales: 1036
Ediciones encontradas: [np.int32(1930), np.int32(1934), np.int32(1938), np.int32(1950), np.int32(1954), np.int32(1958), np.int32(1962), np.int32(1966), np.int32(1970), np.int32(1974), np.int32(1978), np.int32(1982), np.int32(1986), np.int32(1990), np.int32(1994), np.int32(1998), np.int32(2002), np.int32(2006), np.int32(2010), np.int32(2014), np.int32(2018), np.int32(2022), np.int32(2026)]

In [10]:
# Contar partidos por edición (debería ser ~64 desde 1998, ~52 entre 1982-1994, etc.)
wc.groupby('edition').size().to_frame('n_partidos')

         n_partidos
edition
1930             18
1934             17
1938             18
1950             22
1954             26
1958             35
1962             32
1966             32
1970             32
1974             38
1978             38
1982             52
1986             52
1990             52
1994             52
1998             64
2002             64
2006             64
2010             64
2014             64
2018             64
2022             64
2026             72

### Inferencia de fase con heurística por edición

Para mundiales de 32 equipos (1998-2022): 48 partidos de grupos + 16 eliminatorios = 64.  
Distribución eliminatorias: 8 octavos + 4 cuartos + 2 semis + 1 tercer puesto + 1 final.

**Estrategia:** ordenamos los partidos por fecha. Los primeros N corresponden a grupos (donde N se calcula según el formato del año). Los siguientes son eliminatorias en orden inverso de fase (octavos primero, final al final).

In [11]:
def fases_por_edicion(year, n_partidos):
    """Devuelve una lista de fases en orden cronológico para una edición de Mundial.
    
    Reglas heurísticas según formato histórico:
    - 1930-1934: formato variado, marcamos todo como 'Group/Knockout'.
    - 1938: 16 equipos, todo eliminación directa.
    - 1950: round-robin, sin eliminatorias clásicas.
    - 1954-1970: grupos + cuartos + semis + final.
    - 1974-1978: dos rondas de grupos + final.
    - 1982: grupos + segunda ronda grupos + semis + final.
    - 1986-1994: 24 equipos, grupos + octavos + cuartos + semis + tercer puesto + final.
    - 1998-2022: 32 equipos, grupos + octavos + cuartos + semis + tercer puesto + final.
    - 2026: 48 equipos, grupos + 16avos + octavos + cuartos + semis + tercer puesto + final.
    """
    if year >= 1998 and year <= 2022:
        return ['Group'] * 48 + ['Round of 16'] * 8 + ['Quarter-final'] * 4 + \
               ['Semi-final'] * 2 + ['Third-place'] * 1 + ['Final'] * 1
    elif 1986 <= year <= 1994:
        return ['Group'] * 36 + ['Round of 16'] * 8 + ['Quarter-final'] * 4 + \
               ['Semi-final'] * 2 + ['Third-place'] * 1 + ['Final'] * 1
    else:
        # Para formatos antiguos, dejamos genérico y lo refinamos solo si lo necesitamos
        return ['Other'] * n_partidos


fases_asignadas = []
for edicion, grupo in wc.groupby('edition'):
    n = len(grupo)
    fases = fases_por_edicion(edicion, n)
    # Asegurar longitud exacta
    if len(fases) != n:
        fases = fases[:n] if len(fases) > n else fases + ['Other'] * (n - len(fases))
    fases_asignadas.extend(fases)

wc['phase'] = fases_asignadas
wc['phase'].value_counts()

phase
Group            444
Other            432
Round of 16       80
Quarter-final     40
Semi-final        20
Third-place       10
Final             10
Name: count, dtype: int64

## 7. Sanity check con México 🇲🇽

Antes de guardar, verifiquemos que la inferencia funciona: México **debería aparecer eliminado en octavos en cada Mundial de 1994 a 2018**.

In [12]:
mexico_wc = wc[
    ((wc['home_team'] == 'Mexico') | (wc['away_team'] == 'Mexico'))
].copy()

# Última fase alcanzada por edición
PHASE_ORDER = {'Group': 0, 'Round of 16': 1, 'Quarter-final': 2,
               'Semi-final': 3, 'Third-place': 4, 'Final': 5, 'Other': -1}

mexico_wc['phase_rank'] = mexico_wc['phase'].map(PHASE_ORDER)

ultima_fase_mexico = (mexico_wc.groupby('edition')
                                .agg(ultima_fase=('phase', lambda x: x.iloc[x.map(PHASE_ORDER).argmax()]),
                                     n_partidos=('phase', 'size'))
                                .sort_index())
ultima_fase_mexico

           ultima_fase  n_partidos
edition
1930             Other           3
1950             Other           3
1954             Other           2
1958             Other           3
1962             Other           3
1966             Other           3
1970             Other           4
1978             Other           3
1986     Quarter-final           5
1994       Round of 16           4
1998       Round of 16           4
2002       Round of 16           4
2006       Round of 16           4
2010       Round of 16           4
2014       Round of 16           4
2018       Round of 16           4
2022             Group           3
2026             Other           3

## 8. Guardar datos procesados

In [13]:
# Dataset completo limpio (todos los partidos)
df.to_parquet(PROCESSED / 'results_clean.parquet', index=False)
print(f'✅ Guardado: results_clean.parquet ({df.shape[0]:,} filas)')

# Solo Mundiales con fase
wc.to_csv(PROCESSED / 'world_cup_matches.csv', index=False)
print(f'✅ Guardado: world_cup_matches.csv ({wc.shape[0]:,} partidos)')

# Tabla de México para tenerla a mano
ultima_fase_mexico.to_csv(PROCESSED / 'mexico_world_cups.csv')
print(f'✅ Guardado: mexico_world_cups.csv ({len(ultima_fase_mexico)} ediciones)')

✅ Guardado: results_clean.parquet (49,329 filas)
✅ Guardado: world_cup_matches.csv (1,036 partidos)
✅ Guardado: mexico_world_cups.csv (18 ediciones)

## 9. Resumen del notebook

**Lo que hicimos:**
1. Cargamos 47k+ partidos internacionales.
2. Parseamos fechas, validamos tipos.
3. Normalizamos países disueltos (Yugoslavia, USSR, etc.).
4. Etiquetamos tier de torneo (1-4) para usar después en el K-factor del ELO.
5. Inferimos la fase de cada partido del Mundial.
6. Validamos contra México: efectivamente cae en `Round of 16` en 1994, 1998, 2002, 2006, 2010, 2014, 2018, y en `Group` en 2022.

**Próximo notebook (`02_eda.ipynb`):** exploración descriptiva — distribución de goles, evolución temporal, primer vistazo a la ventaja de local.

**Errores comunes que evitamos:**
- ❌ No parsear fechas (queda como string, no se puede ordenar bien).
- ❌ Tratar `West Germany` y `Germany` como países distintos (rompe el ELO histórico).
- ❌ Mezclar amistosos y eliminatorias con el mismo peso (ruido).
- ❌ Asumir que el formato del Mundial es igual desde siempre (no lo es, cambió varias veces).